const posts = [
  {
    title: 'Royal Guards',
    origin: 'Star Wars: Imperial Assault',
    date: '03 May 2021',
    href: 'royal-guards',
  },
  {
    title: 'Snowtroopers',
    origin: 'Star Wars: Imperial Assault',
    date: '26 Apr 2021',
    href: 'snowtroopers',
  },
  {
    title: 'Wampas',
    origin: 'Star Wars: Imperial Assault',
    date: '18 Apr 2021',
    href: 'wampas',
  },
  {
    title: 'Jabba the Hutt',
    origin: 'Star Wars: Imperial Assault',
    date: '11 Apr 2021',
    href: 'jabba-the-hutt',
  },
  {
    title: 'Stormtroopers',
    origin: 'Star Wars: Imperial Assault',
    date: '10 Apr 2021',
    href: 'stormtroopers',
  },
  {
    title: 'Loku Kanoloa',
    origin: 'Star Wars: Imperial Assault',
    date: '27 Mar 2021',
    href: 'loku-kanoloa',
  },
  {
    title: 'Probe Droids',
    origin: 'Star Wars: Imperial Assault',
    date: '24 Mar 2021',
    href: 'probe-droids',
  },
  {
    title: 'Davith Elso',
    origin: 'Star Wars: Imperial Assault',
    date: '14 Mar 2021',
    href: 'davith-elso',
  },
  {
    title: 'Imperial Officers',
    origin: 'Star Wars: Imperial Assault',
    date: '07 Mar 2021',
    href: 'imperial-officers',
  },
  {
    title: 'Shyla Varad',
    origin: 'Star Wars: Imperial Assault',
    date: '06 Mar 2021',
    href: 'shyla-varad',
  },
  {
    title: 'Jet Troopers',
    origin: 'Star Wars: Imperial Assault',
    date: '28 Feb 2021',
    href: 'jet-troopers',
  },
  {
    title: 'Darth Vader',
    origin: 'Star Wars: Imperial Assault',
    date: '15 Feb 2021',
    href: 'darth-vader',
  },
  {
    title: 'Sir Alric Farrow',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '12 Feb 2021',
    href: 'sir-alric-farrow',
  },
  {
    title: 'Lady Eliza Farrow',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '06 Feb 2021',
    href: 'lady-eliza-farrow',
  },
  {
    title: 'Lord Merick Farrow',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '24 Jan 2021',
    href: 'lord-merick-farrow',
  },
  {
    title: 'Elder Mok',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '16 Jan 2021',
    href: 'elder-mok',
  },
  {
    title: 'Karnon',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '10 Jan 2021',
    href: 'karnon',
  },
  {
    title: 'Valyndra',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '29 Dec 2020',
    href: 'valyndra',
  },
  {
    title: 'Cave Spiders',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '24 Dec 2020',
    href: 'cave-spiders',
  },
  {
    title: 'Striders',
    origin: 'Horizon Zero Dawn - The Board Game',
    date: '20 Dec 2020',
    href: 'striders',
  },
  {
    title: 'Belthir',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '15 Dec 2020',
    href: 'belthir',
  },
  {
    title: 'Watchers',
    origin: 'Horizon Zero Dawn - The Board Game',
    date: '10 Dec 2020',
    href: 'watchers',
  },
  {
    title: 'Campaign Battle - Belthir & Sorcerers',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '06 Dec 2020',
    href: 'campaign-battle-01',
  },
  {
    title: 'Sorcerers',
    origin: 'Descent: Journeys in the Dark - Second Edition',
    date: '04 Dec 2020',
    href: 'sorcerers',
  },
  {
    title: 'First Post',
    origin: 'Beginnings',
    date: '03 Dec 2020',
    href: 'first-post',
  },
]

export default posts
