name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          browser: chrome
          build: npm run build
          start: 'npm run test:cy:ci'
          wait-on: http://localhost:7070
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
